/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: AnixMoon (https://sketchfab.com/ani111)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/kda-evelynn-dance-stage-moonlight-edition-404a94a1f65a4379a82db0c3382ffdd9
title: K/DA: Evelynn Dance Stage MoonLight Edition
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
    nodes: {
        Plane005_Logo_0: THREE.Mesh
        Plane006_Floor_0: THREE.Mesh
        Crystal_Crystal_0: THREE.Mesh
        Plane007_Fog_0: THREE.Mesh
        G_Material002_0: THREE.Mesh
        Cube003_Gradient_0: THREE.Mesh
        Plane001__0: THREE.Mesh
        Cylinder102_Neon_0: THREE.Mesh
        Cube005_Material_0: THREE.Mesh
        Light_Lighter_0: THREE.Mesh
    }
    materials: {
        Logo: THREE.MeshStandardMaterial
        Floor: THREE.MeshStandardMaterial
        Crystal: THREE.MeshStandardMaterial
        material: THREE.MeshStandardMaterial
        ['Material.002']: THREE.MeshStandardMaterial
        Gradient: THREE.MeshStandardMaterial
        ['Plane.001__0']: THREE.MeshStandardMaterial
        Neon: THREE.MeshStandardMaterial
        Material: THREE.MeshStandardMaterial
        Lighter: THREE.MeshStandardMaterial
    }
}

export default function DanceStage({ ...props }: JSX.IntrinsicElements['group']) {
    const group = useRef<THREE.Group>()
    const { nodes, materials } = useGLTF('/models/dance-stage/scene-transformed.glb') as GLTFResult
    return (
        //@ts-ignore
        <group ref={group} {...props} dispose={null}>
            <group rotation={[-Math.PI / 2, 0, 0]} scale={0.26}>
                <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
                    <group position={[4509.45, 6431.3, 0]} rotation={[Math.PI, 0, -Math.PI]} scale={100} />
                    {/* <group position={[-3895.21, 7264.17, 0]} rotation={[0, Math.PI / 2, 0]} scale={197.49}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Plane005_Logo_0.geometry}
                            material={materials.Logo}
                        />
                    </group> */}
                    <group
                        position={[-752.67, 5824.78, 0]}
                        rotation={[-Math.PI / 2, 0, 1.05]}
                        scale={[2007.53, 2124.59, 1945.65]}
                    >
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Plane006_Floor_0.geometry}
                            material={materials.Floor}
                        />
                    </group>
                    <group position={[225.33, 6499.1, -951.52]} rotation={[-2.62, 0.97, 0.86]} scale={153.81}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Crystal_Crystal_0.geometry}
                            material={materials.Crystal}
                        />
                    </group>
                    {/* <group
                        position={[-3324.81, 5807.15, -24.94]}
                        rotation={[Math.PI / 2, 0, -Math.PI]}
                        scale={[-4915.19, 4915.19, 4915.19]}
                    >
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Plane007_Fog_0.geometry}
                            material={materials.material}
                        />
                    </group> */}
                    {/* <group
                        position={[-3324.81, 5807.15, -24.94]}
                        rotation={[Math.PI / 2, 0, -Math.PI]}
                        scale={[-4915.19, 4915.19, 4915.19]}
                    >
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.G_Material002_0.geometry}
                            material={materials['Material.002']}
                        />
                    </group> */}
                    <group
                        position={[-5463.4, 7030.57, 15.34]}
                        rotation={[-Math.PI / 2, 0, Math.PI / 2]}
                        scale={884.54}
                    >
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Cube003_Gradient_0.geometry}
                            material={materials.Gradient}
                        />
                    </group>
                    <group position={[-7456.63, 4610.77, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Plane001__0.geometry}
                            material={materials['Plane.001__0']}
                        />
                    </group>
                    <group
                        position={[-5747.64, 8415.72, -2563.25]}
                        rotation={[-1.3, 0.04, -0.17]}
                        scale={[22.28, 22.28, 2644.52]}
                    >
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Cylinder102_Neon_0.geometry}
                            material={materials.Neon}
                        />
                    </group>
                    <group
                        position={[-5463.4, 4377.85, 15.34]}
                        rotation={[Math.PI / 2, 0, Math.PI / 2]}
                        scale={[-884.54, 884.54, 884.54]}
                    >
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Cube005_Material_0.geometry}
                            material={materials.Material}
                        />
                    </group>
                    <group
                        position={[-5463.4, 7030.57, 15.34]}
                        rotation={[-Math.PI / 2, 0, Math.PI / 2]}
                        scale={884.54}
                    >
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Light_Lighter_0.geometry}
                            material={materials.Lighter}
                        />
                    </group>
                </group>
            </group>
        </group>
    )
}

useGLTF.preload('/scene-transformed.glb')
